print("**** A simple forms using Python ***")
Myname = input("whats is your name?  ")
age = input("how old are you? ")
email = input("input your email: ")
print()
print("Your name is " + Myname)
print("Your email address is")
print(email)
print("Your are", age, "years old")
print("new forms")
